//AUTOGENERATED FILE FROM png2asset
// Conversion args: \bg.png -c \bg.c -map -bpp 2 -bin -tile_origin 100

#ifndef METASPRITE_bg_H
#define METASPRITE_bg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_TILE_ORIGIN 100
#define bg_TILE_W 8
#define bg_TILE_H 8
#define bg_WIDTH 256
#define bg_HEIGHT 256
#define bg_TILE_COUNT 87
#define bg_PALETTE_COUNT 1
#define bg_COLORS_PER_PALETTE 4
#define bg_TOTAL_COLORS 4
#define bg_MAP_ATTRIBUTES 0
extern const unsigned char bg_map[1024];
#define bg_map_attributes bg_map

BANKREF_EXTERN(bg)

extern const palette_color_t bg_palettes[4];
extern const uint8_t bg_tiles[1392];

#endif
