//AUTOGENERATED FILE FROM png2asset
// Conversion args: /chr_gb_flipped.png -c /chr_gb_flipped.c -map -bin -keep_duplicate_tiles -noflip

#ifndef METASPRITE_chr_gb_flipped_H
#define METASPRITE_chr_gb_flipped_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define chr_gb_flipped_TILE_ORIGIN 0
#define chr_gb_flipped_TILE_W 8
#define chr_gb_flipped_TILE_H 8
#define chr_gb_flipped_WIDTH 128
#define chr_gb_flipped_HEIGHT 128
#define chr_gb_flipped_TILE_COUNT 256
#define chr_gb_flipped_PALETTE_COUNT 4
#define chr_gb_flipped_COLORS_PER_PALETTE 4
#define chr_gb_flipped_TOTAL_COLORS 16
#define chr_gb_flipped_MAP_ATTRIBUTES 0
extern const unsigned char chr_gb_flipped_map[256];
#define chr_gb_flipped_map_attributes chr_gb_flipped_map

BANKREF_EXTERN(chr_gb_flipped)

extern const palette_color_t chr_gb_flipped_palettes[16];
extern const uint8_t chr_gb_flipped_tiles[4096];

#endif
