//AUTOGENERATED FILE FROM png2asset
// Conversion args: /chr_gb_neww.png -map -bin -tiles_only -noflip -keep_duplicate_tiles

#ifndef METASPRITE_chr_gb_neww_H
#define METASPRITE_chr_gb_neww_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define chr_gb_neww_TILE_ORIGIN 0
#define chr_gb_neww_TILE_W 8
#define chr_gb_neww_TILE_H 8
#define chr_gb_neww_WIDTH 128
#define chr_gb_neww_HEIGHT 128
#define chr_gb_neww_TILE_COUNT 256
#define chr_gb_neww_PALETTE_COUNT 3
#define chr_gb_neww_COLORS_PER_PALETTE 4
#define chr_gb_neww_TOTAL_COLORS 12

BANKREF_EXTERN(chr_gb_neww)

extern const palette_color_t chr_gb_neww_palettes[12];
extern const uint8_t chr_gb_neww_tiles[4096];

#endif
