//AUTOGENERATED FILE FROM png2asset
// Conversion args: \bg_contrasted.png -o \bg_contrasted.c -map -bpp 2 -bin -tile_origin 28 -noflip

#ifndef METASPRITE_bg_contrasted_H
#define METASPRITE_bg_contrasted_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_contrasted_TILE_ORIGIN 28
#define bg_contrasted_TILE_W 8
#define bg_contrasted_TILE_H 8
#define bg_contrasted_WIDTH 256
#define bg_contrasted_HEIGHT 256
#define bg_contrasted_TILE_COUNT 87
#define bg_contrasted_PALETTE_COUNT 1
#define bg_contrasted_COLORS_PER_PALETTE 4
#define bg_contrasted_TOTAL_COLORS 4
#define bg_contrasted_MAP_ATTRIBUTES 0
extern const unsigned char bg_contrasted_map[1024];
#define bg_contrasted_map_attributes bg_contrasted_map

BANKREF_EXTERN(bg_contrasted)

extern const palette_color_t bg_contrasted_palettes[4];
extern const uint8_t bg_contrasted_tiles[1392];

#endif
