//AUTOGENERATED FILE FROM png2asset
// Conversion args: \menu_ground.png -o \menu_ground.c -map -bpp 2 -bin -tile_origin 115 -noflip

#ifndef METASPRITE_menu_ground_H
#define METASPRITE_menu_ground_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menu_ground_TILE_ORIGIN 115
#define menu_ground_TILE_W 8
#define menu_ground_TILE_H 8
#define menu_ground_WIDTH 256
#define menu_ground_HEIGHT 24
#define menu_ground_TILE_COUNT 9
#define menu_ground_PALETTE_COUNT 1
#define menu_ground_COLORS_PER_PALETTE 4
#define menu_ground_TOTAL_COLORS 4
#define menu_ground_MAP_ATTRIBUTES 0
extern const unsigned char menu_ground_map[96];
#define menu_ground_map_attributes menu_ground_map

BANKREF_EXTERN(menu_ground)

extern const palette_color_t menu_ground_palettes[4];
extern const uint8_t menu_ground_tiles[144];

#endif
