//AUTOGENERATED FILE FROM png2asset
// Conversion args: /bg_shifted.png -o /bg_shifted.c -map -bpp 2 -bin -tile_origin 28 -noflip

#ifndef METASPRITE_bg_shifted_H
#define METASPRITE_bg_shifted_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_shifted_TILE_ORIGIN 28
#define bg_shifted_TILE_W 8
#define bg_shifted_TILE_H 8
#define bg_shifted_WIDTH 256
#define bg_shifted_HEIGHT 256
#define bg_shifted_TILE_COUNT 89
#define bg_shifted_PALETTE_COUNT 1
#define bg_shifted_COLORS_PER_PALETTE 4
#define bg_shifted_TOTAL_COLORS 4
#define bg_shifted_MAP_ATTRIBUTES 0
extern const unsigned char bg_shifted_map[1024];
#define bg_shifted_map_attributes bg_shifted_map

BANKREF_EXTERN(bg_shifted)

extern const palette_color_t bg_shifted_palettes[4];
extern const uint8_t bg_shifted_tiles[1424];

#endif
