// Auto-generated by tools/build_levels.py - DO NOT EDIT DIRECTLY
#include <gbdk/incbin.h>
#include "assets.h"
#include "../levels/chr_data/chr_gb.h"

BANKREF(game_levels)
BANKREF_EXTERN(chr_gb)
extern const uint8_t chr_gb_tiles[];
extern const uint8_t chr_gb_tiles_rev[];

// External map data definitions from level files
BANKREF_EXTERN(stereomadness_map)
extern const uint8_t stereomadness_map[];
BANKREF_EXTERN(backontrack_map)
extern const uint8_t backontrack_map[];
BANKREF_EXTERN(polargeist_map)
extern const uint8_t polargeist_map[];
BANKREF_EXTERN(dryout_map)
extern const uint8_t dryout_map[];
BANKREF_EXTERN(baseafterbase_map)
extern const uint8_t baseafterbase_map[];
BANKREF_EXTERN(cantletgo_map)
extern const uint8_t cantletgo_map[];
BANKREF_EXTERN(jumper_map)
extern const uint8_t jumper_map[];
BANKREF_EXTERN(timemachine_map)
extern const uint8_t timemachine_map[];
BANKREF_EXTERN(cycles_map)
extern const uint8_t cycles_map[];
BANKREF_EXTERN(xstep_map)
extern const uint8_t xstep_map[];
BANKREF_EXTERN(ultiatedestruction_map)
extern const uint8_t ultiatedestruction_map[];

// External sprite data definitions
extern const SpDef stereomadness_sp[];
extern const SpDef stereomadness_sp_dmg[];
BANKREF_EXTERN(stereomadness_sp)
extern const SpDef backontrack_sp[];
extern const SpDef backontrack_sp_dmg[];
BANKREF_EXTERN(backontrack_sp)
extern const SpDef polargeist_sp[];
extern const SpDef polargeist_sp_dmg[];
BANKREF_EXTERN(polargeist_sp)
extern const SpDef dryout_sp[];
extern const SpDef dryout_sp_dmg[];
BANKREF_EXTERN(dryout_sp)
extern const SpDef baseafterbase_sp[];
extern const SpDef baseafterbase_sp_dmg[];
BANKREF_EXTERN(baseafterbase_sp)
extern const SpDef cantletgo_sp[];
extern const SpDef cantletgo_sp_dmg[];
BANKREF_EXTERN(cantletgo_sp)
extern const SpDef jumper_sp[];
extern const SpDef jumper_sp_dmg[];
BANKREF_EXTERN(jumper_sp)
extern const SpDef timemachine_sp[];
extern const SpDef timemachine_sp_dmg[];
BANKREF_EXTERN(timemachine_sp)
extern const SpDef cycles_sp[];
extern const SpDef cycles_sp_dmg[];
BANKREF_EXTERN(cycles_sp)
extern const SpDef xstep_sp[];
extern const SpDef xstep_sp_dmg[];
BANKREF_EXTERN(xstep_sp)
extern const SpDef ultiatedestruction_sp[];
extern const SpDef ultiatedestruction_sp_dmg[];
BANKREF_EXTERN(ultiatedestruction_sp)

// Music songs
extern const hUGESong_t stereomadness;
extern const hUGESong_t backontrack;
extern const hUGESong_t polargeist;
extern const hUGESong_t dryout;
extern const hUGESong_t baseafterbase;
extern const hUGESong_t cantletgo;
extern const hUGESong_t jumper;
extern const hUGESong_t timemachine;
extern const hUGESong_t cycles;
extern const hUGESong_t xstep;
extern const hUGESong_t ultiatedestruction;

// Level songs array
const hUGESong_t * const level_songs[] = {
  &stereomadness, // level_sm
  &backontrack, // level_bot
  &polargeist, // level_pg
  &dryout, // level_du
  &baseafterbase, // level_bab
  &cantletgo, // level_clg
  &jumper, // level_ju
  &timemachine, // level_tm
  &cycles, // level_cy
  &xstep, // level_xs
  &ultiatedestruction, // level_ultiatedestruction
};

// Per-level song banks: matches level_songs[]; 0 = silent
const uint8_t song_bank[] = {
  200u, // level_sm
  201u, // level_bot
  202u, // level_pg
  203u, // level_du
  204u, // level_bab
  205u, // level_clg
  206u, // level_ju
  207u, // level_tm
  208u, // level_cy
  209u, // level_xs
  210u, // level_ultiatedestruction
};

// Level definitions with dimensions and bank info
const Level level_sm = {
  "STEREO MADNESS",
  chr_gb_tiles,
  chr_gb_tiles_rev,
  stereomadness_map,
  chr_gb_TILE_COUNT, 894, 16, 0, 0,
  BANK(stereomadness_map),
  192,
  stereomadness_sp,
  BANK(stereomadness_sp),
  stereomadness_sp_dmg
};

const Level level_bot = {
  "BACK ON TRACK",
  chr_gb_tiles,
  chr_gb_tiles_rev,
  backontrack_map,
  chr_gb_TILE_COUNT, 846, 16, 0, 0,
  BANK(backontrack_map),
  184,
  backontrack_sp,
  BANK(backontrack_sp),
  backontrack_sp_dmg
};

const Level level_pg = {
  "POLARGEIST",
  chr_gb_tiles,
  chr_gb_tiles_rev,
  polargeist_map,
  chr_gb_TILE_COUNT, 935, 16, 0, 0,
  BANK(polargeist_map),
  193,
  polargeist_sp,
  BANK(polargeist_sp),
  polargeist_sp_dmg
};

const Level level_du = {
  "DRY OUT",
  chr_gb_tiles,
  chr_gb_tiles_rev,
  dryout_map,
  chr_gb_TILE_COUNT, 842, 16, 0, 0,
  BANK(dryout_map),
  185,
  dryout_sp,
  BANK(dryout_sp),
  dryout_sp_dmg
};

const Level level_bab = {
  "BASE AFTER BASE",
  chr_gb_tiles,
  chr_gb_tiles_rev,
  baseafterbase_map,
  chr_gb_TILE_COUNT, 869, 16, 0, 0,
  BANK(baseafterbase_map),
  183,
  baseafterbase_sp,
  BANK(baseafterbase_sp),
  baseafterbase_sp_dmg
};

const Level level_clg = {
  "CANT LET GO",
  chr_gb_tiles,
  chr_gb_tiles_rev,
  cantletgo_map,
  chr_gb_TILE_COUNT, 837, 16, 0, 0,
  BANK(cantletgo_map),
  196,
  cantletgo_sp,
  BANK(cantletgo_sp),
  cantletgo_sp_dmg
};

const Level level_ju = {
  "JUMPER",
  chr_gb_tiles,
  chr_gb_tiles_rev,
  jumper_map,
  chr_gb_TILE_COUNT, 897, 16, 0, 0,
  BANK(jumper_map),
  141,
  jumper_sp,
  BANK(jumper_sp),
  jumper_sp_dmg
};

const Level level_tm = {
  "TIME MACHINE",
  chr_gb_tiles,
  chr_gb_tiles_rev,
  timemachine_map,
  chr_gb_TILE_COUNT, 997, 16, 0, 0,
  BANK(timemachine_map),
  40,
  timemachine_sp,
  BANK(timemachine_sp),
  timemachine_sp_dmg
};

const Level level_cy = {
  "CYCLES",
  chr_gb_tiles,
  chr_gb_tiles_rev,
  cycles_map,
  chr_gb_TILE_COUNT, 823, 16, 0, 0,
  BANK(cycles_map),
  183,
  cycles_sp,
  BANK(cycles_sp),
  cycles_sp_dmg
};

const Level level_xs = {
  "XSTEP",
  chr_gb_tiles,
  chr_gb_tiles_rev,
  xstep_map,
  chr_gb_TILE_COUNT, 844, 16, 0, 0,
  BANK(xstep_map),
  138,
  xstep_sp,
  BANK(xstep_sp),
  xstep_sp_dmg
};

const Level level_ultiatedestruction = {
  "UTLIMATE DESTCTN",
  chr_gb_tiles,
  chr_gb_tiles_rev,
  ultiatedestruction_map,
  chr_gb_TILE_COUNT, 675, 16, 0, 0,
  BANK(ultiatedestruction_map),
  183,
  ultiatedestruction_sp,
  BANK(ultiatedestruction_sp),
  ultiatedestruction_sp_dmg
};

// Global level list used by the menu and gameplay systems
const Level* const game_levels[] = {
  &level_sm,
  &level_bot,
  &level_pg,
  &level_du,
  &level_bab,
  &level_clg,
  &level_ju,
  &level_tm,
  &level_cy,
  &level_xs,
  &level_ultiatedestruction,
};
const uint8_t MAX_LEVELS = sizeof(game_levels) / sizeof(game_levels[0]);
