name: Build ROM and Music

on:
  push:
    paths:
      - 'src/**'
      - 'makefile'
      - 'music/**'
      - 'processers/**'
      - '*'
      - '.github/**'
  pull_request:
    paths:
      - 'src/**'
      - 'makefile'
      - 'music/**'
      - 'processers/**'
      - '*'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Process Music Files
        run: |
          python processtotxt.py
          python TXTtoJSON.py

      - name: Upload Processed Music
        uses: actions/upload-artifact@v4
        with:
          name: Processed Music
          path: music/

      - name: Compile GameBoy ROM
        run: |
          make

      - name: Upload GameBoy ROM
        uses: actions/upload-artifact@v4
        with:
          name: ROM
          path: build/
