name: Build ROM

on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
      - 'makefile'
  pull_request:
    paths:
      - 'src/**'
      - 'makefile'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile GameBoy ROM
        run: |
          & ".\build.bat"

      - name: Upload GameBoy ROM
        uses: actions/upload-artifact@v4
        with:
          name: ROM
          path: build/
