name: Process Music

on:
  push:
    paths:
      - 'music/**'
      - 'processers/**'
      - '.github/**'
  pull_request:
    paths:
      - 'music/**'
      - 'processers/**'

jobs:
  process_music:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make tools executable
        run: |
          chmod +x processers/LSDJ/lsdj2txt
          chmod +x processers/FUR/furnace

      - name: Process Music Files
        run: |
          python processtotxt.py
          python TXTtoJSON.py

      - name: Upload Processed Music
        uses: actions/upload-artifact@v4
        with:
          name: Processed Music
          path: music/
